#!/usr/bin/env bash

set -euo pipefail


readonly LOG_DIR="/var/log/${PACKAGE_NAME}"
readonly LOG_FILE="${LOG_DIR}/${PACKAGE_NAME}.log"
readonly LOG_DISK_FILE="${LOG_DIR}/${PACKAGE_NAME}_disk.log"
readonly LOG_CPU_FILE="${LOG_DIR}/${PACKAGE_NAME}_cpu.log"
readonly LOG_MEMORY_FILE="${LOG_DIR}/${PACKAGE_NAME}_mem.log"

LOG_FORMAT=$(date +%Y-%m-%d-%H:%m:%S)

